version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_controller.yaml
    flatten: true
    excludes: [ ] # put task names in here which are overwritten in this file
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/landscaper-cli/... {{.ROOT_DIR}}/pkg/... {{.ROOT_DIR}}/integration-test/...'
      COMPONENTS: landscapercli
      REPO_URL: 'https://github.com/openmcp-project/landscapercli'
      GENERATE_DOCS_INDEX: "false"
      CHART_COMPONENTS: "[]"
