name: CI

on:
  push:
    tags:
      - v*
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_validate_test:
    uses: openmcp-project/build/.github/workflows/ci.lib.yaml@65e6b16460f72253e95d292f8c58fd9e5affa9fd # main
    secrets: inherit
