name: CI

on:
  push:
    tags:
      - v*
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_validate_test:
    uses: openmcp-project/build/.github/workflows/ci.lib.yaml@b502e7a3478ba1944abb4a69aea548d115721e96 # main
    secrets: inherit
