name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@65e6b16460f72253e95d292f8c58fd9e5affa9fd # main
    secrets: inherit
