name: Validate Pull Request Content

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  validate_pr_content:
    uses: openmcp-project/build/.github/workflows/validate-pr-content.lib.yaml@65e6b16460f72253e95d292f8c58fd9e5affa9fd # main
    secrets: inherit